
# xboot is a submodule so we need to include it
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - compliance
  - build

before_script:
  - apt install -y ruby
  - west init -l . || true
  - west update --path-cache /cache/x3
  

check_compliance:
  stage: compliance
  extends: .build-job
  script:
    - export ZEPHYR_BASE=$PWD/../zephyr
    - ls -la
    - git log  --pretty=oneline -n 10
    - git diff --cached | ${ZEPHYR_BASE}/scripts/checkpatch.pl --ignore BRACES - || false
    
firmware:
  stage: build
  extends: .build-job
  script:
    - export BUILD_NUMBER=$(($CI_PIPELINE_IID + 1000))
    - printf "$BUILD_NUMBER" > buildnumber
    - printf "$CI_COMMIT_SHA" 
    - ../zephyr/scripts/twister -i -T tests/
#    - west build -p

.build-job:
  image: registry.gitlab.com/nofence/x3-fw-app/x3-firmware-ci

     
  
