
# xboot is a submodule so we need to include it
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

before_script:
  - apt install -y ruby

firmware:
  stage: build
  extends: .build-job
  script:
    - export BUILD_NUMBER=$(($CI_PIPELINE_IID + 1000))
    - printf "$BUILD_NUMBER" > buildnumber
    - printf "$CI_COMMIT_SHA" 
    - >
      if [ ! -d ../zephyr/ ]; then 
        west init -l .
      fi
    - west update
    - ../zephyr/scripts/twister -i -T tests/

.build-job:
  image: zephyrprojectrtos/ci
  
