
# xboot is a submodule so we need to include it
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - .pre
  - build

before_script:
  - apt install -y ruby

check_compliance:
  stage: .pre
  extends: .build-job
  script:
    - export ZEPHYR_BASE=$PWD/../zephyr
    - ls -la
    - git log  --pretty=oneline | head -n 10
  #  - # git diff --cached | ${ZEPHYR_BASE}/scripts/checkpatch.pl --ignore BRACES - || false


firmware:
  stage: build
  extends: .build-job
  script:
    - export BUILD_NUMBER=$(($CI_PIPELINE_IID + 1000))
    - printf "$BUILD_NUMBER" > buildnumber
    - printf "$CI_COMMIT_SHA" 
    - west init -l . || true
    - west update
    - ../zephyr/scripts/twister -i -T tests/

.build-job:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/zephyrprojectrtos/ci
  
