# Example application-specific west.yml, using manifest imports.
manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: nofence
      url-base: git@gitlab.com:nofence
  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: ncs
      revision: v1.6.1
      import: true
    - name: collar-protocol
      remote: nofence
      repo-path: collar-protocol
      revision: initial_copy

  self:
    path: application
